#!/bin/bash

GIT_ROOT='/c/GIT'

alias suivi="cd /c/Users/T357275/Desktop/suivi ; ./MEMO.sh"
alias app_version='mvn help:evaluate -Dexpression=project.version -B -q -DforceStdout'
TODOFILE="/c/Users/T357275/Desktop/BASHRC/todo.list"
RAZ_STYLE="\e[0m"
BLUE_STYLE="\e[0;49;96m"
PURPLE_STYLE="\e[1;40;35m"
RED_STYLE="\e[91m"
GREEN_STYLE="\e[38;5;82m"
PROMPT_STYLE="\e[0;49;92m"
ORANGE_STYLE="\e[0;40;93m"
